### PR TITLE
Add sourcemaps for decorated snippet code

### PR DESCRIPTION
**Pull request by fvictorio**
This undoes your carefully crafted code in `injectDependencies` and is very ugly, but I wanted to start a discussion around this.

### CODE REVIEW

**Comment by fvictorio** [comment]
Btw, I didn't update the snapshots because I wanted to discuss some things first. For example, is removing the dependencies worth it if it makes more complex the code and sourcemaps generation? (It's not that hard, but a little more involved).

**Comment by fvictorio** [comment]
What do you think we should do here before we can merge this?

**Comment by gillchristian** [comment]
If we are going to leave the dumped snippets files we should give them some name, maybe file and number (i.e `snjppet-README.MD-6.js`). Also I'd add the option to leave the files as opt in, or maybe move them to other directory. Some kind of cleanup.

**Comment by fvictorio** [comment]
They are being removed right now, aren't they?

**Comment by fvictorio** [comment]
What do we need to do before merging this PR?

**Comment by gillchristian** [comment]
Yes, they are. I missed it my bad.

I'm getting this error when running the example

```dev/chimi/example on  add-source-maps [$!?] is 📦  v1.0.0 via ⬢ v8.6.0 
•100% $ yarn test
yarn run v1.2.0
$ ../bin/bin.js
⠙ Running snippets.events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:354:12)
    at Computation.Future [as _computation] (/home/gillchristian/dev/chimi/lib/run-snippet.js:54:17)
    at Computation$_fork [as _fork] (/home/gillchristian/dev/chimi/node_modules/fluture/index.js:474:16)
    at drain (/home/gillchristian/dev/chimi/node_modules/fluture/index.js:232:25)
    at settle (/home/gillchristian/dev/chimi/node_modules/fluture/index.js:161:17)
    at resolved (/home/gillchristian/dev/chimi/node_modules/fluture/index.js:175:5)
    at Computation$res (/home/gillchristian/dev/chimi/node_modules/fluture/index.js:482:7)
    at ChildProcess.child.on (/home/gillchristian/dev/chimi/lib/run-snippet.js:43:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gillchristian** [comment]
Tests and snapshots are updated, we could merge this but I'd prefer to solve the error first.

**Comment by gillchristian** [comment]
We have a problem with the process sometimes never ending. Yes, again ( #15 ). I don't know if it was introduced after this PR, but I think we merge it and investigate that separately.

**Pull request merged**
